Migration to DynamoDB
ioet/cmd-server pull request #2
Opened 2018-04-04 21:15 UTC by Boscoand

In this code, we have migrate to Dynamo DB from CassandraDB. Also, we have include Dynamoose that is a ORM for Dynamo.

2018-04-05 21:20 UTC, bitcod3r requested changes

2018-04-05 21:20 UTC, bitcod3r commented on src/config/configDB.js
> +  region: 'us-east-1'
Please, change this parameter "region" to .env private file.

2018-04-05 21:20 UTC, bitcod3r commented on src/index.js
> +app.listen(process.env.APP_PORT, () => console.log("Running on localhost: " + process.env.APP_PORT))
Please, add the app version number in this console.log.

2018-04-05 21:20 UTC, bitcod3r commented on src/routes/auth.js
> +/*router.post('/register', (req, res) => {
Refactor the registration methods to use Dynamo.

2018-04-05 21:20 UTC, bitcod3r commented on src/errors/errors.auth.js
> +        res.status(400).json({errors: { global: "Error from database connection." } })
Print in console the error details.

2018-04-06 16:36 UTC, Boscoand commented on src/index.js
> +app.listen(process.env.APP_PORT, () => console.log("Running on localhost: " + process.env.APP_PORT))
Which is the first version? 0.0.1?

2018-04-06 22:36 UTC, bitcod3r commented on src/errors/errors.auth.js
> +        res.status(400).json({errors: { global: "Error from database connection." } })
good job!

2018-04-06 22:49 UTC, bitcod3r approved these changes

2018-04-06 22:54 UTC, merged